version: '3'

services:
  db:
    container_name: db-container
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - db-container-data:/var/lib/postgresql/data

volumes:
  db-container-data: