version: '3'

services:
  frontend:
    container_name: frontend-container
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.multi-stage
    restart: on-failure
    ports:
      - "3000:80"

  backend:
    container_name: backend-container
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.multi-stage
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: db-container
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - db-container-data:/var/lib/postgresql/data

volumes:
  db-container-data: