# Stage 1: Build the backend app
FROM node:latest as builder

LABEL maintainer="Ícaro Ribeiro <icaroribeiro@hotmail.com>"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run lint
RUN npm run build

# Stage 2: Create the backend production image
FROM node:slim as production

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /app/dist ./

CMD ["node", "--env-file .env", "./index.js"]