# Stage 1: Build the backend application image
FROM node:latest as builder

LABEL maintainer="Ícaro Ribeiro <icaroribeiro@hotmail.com>"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Build the backend application image for production environment
FROM node:slim as production

WORKDIR /app

COPY --from=builder /app/dist .
COPY --from=builder /app/.env.prod .

CMD ["node", "--env-file .env", "index.js"]
