CREATE TABLE IF NOT EXISTS addrs_distance_history (
    id uuid NOT NULL,
    src_addr_amenity text NOT NULL,
    src_addr_street text NOT NULL,
    src_addr_city text NOT NULL,
    src_addr_county text NOT NULL,
    src_addr_state text NOT NULL,
    src_addr_country text NOT NULL,
    src_addr_postalcode text NOT NULL,
    dst_addr_amenity text NOT NULL,
    dst_addr_street text NOT NULL,
    dst_addr_city text NOT NULL,
    dst_addr_county text NOT NULL,
    dst_addr_state text NOT NULL,
    dst_addr_country text NOT NULL,
    dst_addr_postalcode text NOT NULL,
    distance numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT addrs_distance_history_pkey PRIMARY KEY (id)
);
